# Generated by Django 3.0.8 on 2020-07-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200710_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='markdown',
            field=models.BooleanField(default=False),
        ),
    ]
