# Generated by Django 3.0.8 on 2020-07-10 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_note_markdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notes',
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
