# Generated by Django 3.0.8 on 2020-07-10 01:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200710_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
