# Generated by Django 3.0.8 on 2020-07-11 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200711_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='public',
        ),
        migrations.AlterField(
            model_name='note',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.Path'),
        ),
    ]
