# Generated by Django 3.0.8 on 2020-07-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200712_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='path',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
