# Generated by Django 3.0.8 on 2020-07-12 00:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200712_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed. First character can not be digit.')]),
        ),
    ]
