# Generated by Django 3.0.8 on 2020-07-12 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200712_0338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='owner',
        ),
    ]
