# Generated by Django 3.0.8 on 2020-07-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_note_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
