// App
export const CHANGE_APP_TITLE = 'CHANGE_APP_TITLE'
export const HIDE_NAV = 'HIDE_NAV'
export const SHOW_NAV = 'SHOW_NAV'

// Auth
export const LOGIN_BEGIN = 'LOGIN_BEGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOGOUT_BEGIN = 'LOGOUT_BEGIN'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'

export const UPDATE_PROFILE_BEGIN = 'UPDATE_PROFILE_BEGIN'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR'

export const SET_PROFILE = 'SET_PROFILE'

export const REFRESH_TOKEN = 'REFRESH_TOKEN'
