// App
export const CHANGE_APP_TITLE = 'CHANGE_APP_TITLE'

// Auth
export const LOGIN_BEGIN = 'LOGIN_BEGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOGOUT_BEGIN = 'LOGOUT_BEGIN'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'

export const UPDATE_PROFILE_BEGIN = 'UPDATE_PROFILE_BEGIN'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR'

export const REFRESH_TOKEN = 'REFRESH_TOKEN'

// Note
export const FETCH_NOTE_BEGIN = 'FETCH_NOTE_BEGIN'
export const FETCH_NOTE_SUCCESS = 'FETCH_NOTE_SUCCESS'
export const FETCH_NOTE_ERROR = 'FETCH_NOTE_ERROR'

export const CREATE_NOTE_BEGIN = 'CREATE_NOTE_BEGIN'
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS'
export const CREATE_NOTE_ERROR = 'CREATE_NOTE_ERROR'

export const CHANGE_NOTE_PASSWORD_BEGIN = 'CHANGE_NOTE_PASSWORD_BEGIN'
export const CHANGE_NOTE_PASSWORD_SUCCESS = 'CHANGE_NOTE_PASSWORD_SUCCESS'
export const CHANGE_NOTE_PASSWORD_ERROR = 'CHANGE_NOTE_PASSWORD_ERROR'

export const SET_NOTE_TEXT = 'SET_NOTE_TEXT'
